### ISSUE TITLE
Crashes after having processed a lot of images

### ISSUE THREAD

**Issue by johan-andersson01** [johan-andersson01/photo_organizer#10]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full
```
This occurs after processing 41148 images.

One theory is that processes have been throwing a lot of exceptions and putting them inside a queue, and now that queue is full.

**Comment by johan-andersson01** [comment]
Another theory is that there are some videos that are too large to be sent through pipes, crashing one subprocess after which the main process sends poision pills to the rest.

**Comment by johan-andersson01** [comment]
After having excluded a folder with large video files (~2.5GB), the process did not crash.

It seems then that the previous comment might be on to something.

**Comment by johan-andersson01** [comment]
This should preferably be solved by copying the file to `failed` and logging that the file was too big.

**Comment by johan-andersson01** [comment]
Funny how time changes your perception...

In hindsight it is obvious that the issue was this function:

```
def files_equal(f1: Path, f2: Path) -> bool:
    return open(f1, 'rb').read() == open(f2, 'rb').read()
```

A process crashes if the filesize of `f1` + `f2` is too big to fit in memory. 

The error `queue.Full` was therefore likely raised because too many processes encountered this situation.

As of 723664, this is fixed by using threads and an error mutex, shutting down all threads if any unforeseen error occurs.
